#!/usr/bin/python


from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.common.text.converters import to_native
import os
import json
import re

def generate_rego_content(package, rules):
    """Constructs the primary Rego policy logic, correctly handling single/multiple rules."""
    
    lines = [
        f"package {package}",
        "import rego.v1",
        "",
        '# Generated by Ansible Policy Factory',
        'default allow := {"allowed": true, "violations": []}',
    ]
    

    for i, rule in enumerate(rules, 1):
        r_type = rule.get('type')
        attr = rule.get('check_attribute')
        
        lines.append(f"\n# Rule {i}: {rule.get('description', 'Auto-generated')}")
        
    
        lines.append("violations contains msg if {")
        lines.append(f"    _check_rule_{i}")
        lines.append(f'    msg := "{rule.get("error_msg", "Policy Violation")}"')
        lines.append("}")


        lines.append(f"_check_rule_{i} if {{")
        
        if rule.get('condition'):
            lines.append(f"    {rule['condition']}")
        if r_type == 'block_list':
            vals = json.dumps(rule.get('blocked_values', []))
            lines.append(f"    {attr} == {vals}[_]")
        elif r_type == 'group_block_list':
            vals = json.dumps(rule.get('blocked_values', []))
            lines.append(f"    {attr}[_] == {vals}[_]")
        elif r_type == 'deny_match':
            pattern = rule.get('prohibited_pattern', '')
            lines.append(f'    contains({attr}, "{pattern}")')
            
        lines.append("}") # Close _check_rule_i
    

    lines.append("\n# Final decision: Deny if violation set is not empty.")
    lines.append('allow := {"allowed": false, "violations": violations} if count(violations) > 0')
    
    return "\n".join(lines)

def generate_test_content(package, rules):
    """Constructs unit tests with nested mock input generation."""
    lines = [f"package {package}", "import rego.v1", "", "# Unit Tests"]
    
    for i, rule in enumerate(rules, 1):
        test_name = rule.get('name', f'rule_{i}').lower().replace(' ', '_')
        lines.append(f"test_{test_name}_denied if {{")
        
        mock_input = {}

        
        condition = rule.get('condition', '')
        if '==' in condition:
            match = re.search(r'input\.([\w\.]+)\s*==\s*"([^"]+)"', condition)
            if match:
                path, val = match.groups()
                curr = mock_input
                parts = path.split('.')
                for part in parts[:-1]:
                    curr[part] = curr.get(part, {})
                    curr = curr[part]
                curr[parts[-1]] = val

        
        attr_path = rule.get('check_attribute', '').replace('input.', '').split('.')
        r_type = rule.get('type')
        
        if r_type == 'group_block_list':
            blocked_val = [rule.get('blocked_values', ["restricted_group"])[0]]
        elif r_type == 'block_list':
            blocked_val = rule.get('blocked_values', ["forbidden"])[0]
        else:
            blocked_val = rule.get('prohibited_pattern', 'forbidden')
        
        curr = mock_input
        for part in attr_path[:-1]:
            curr[part] = curr.get(part, {})
            curr = curr[part]
        curr[attr_path[-1]] = blocked_val

        lines.append(f"    mock_input := {json.dumps(mock_input)}")
        lines.append(f"    res := allow with input as mock_input")
        lines.append(f"    res.allowed == false")
        lines.append("}\n")
    
    return "\n".join(lines)


def run_module():
    module_args = dict(
        rules=dict(type='list', required=True),
        package=dict(type='str', required=True),
        dest=dict(type='path', required=True)
    )

    module = AnsibleModule(argument_spec=module_args)
    dest_path = module.params['dest']
    test_path = dest_path.replace('.rego', '_test.rego')
    
    try:
        policy_code = generate_rego_content(module.params['package'], module.params['rules'])
        test_code = generate_test_content(module.params['package'], module.params['rules'])
        
        os.makedirs(os.path.dirname(dest_path), exist_ok=True)
        
        with open(dest_path, 'w') as f: f.write(policy_code)
        with open(test_path, 'w') as f: f.write(test_code)
            
        module.exit_json(changed=True, policy_dest=dest_path, test_dest=test_path)
    except Exception as e:
        module.fail_json(msg=f"Internal Generator Error: {to_native(e)}")

if __name__ == '__main__':
    run_module()